### ISSUE TITLE
Tried for 2.0.3.1

### ISSUE THREAD

**Issue by aljawaid** [mochacat/OC_EngagementPro#1]
I tried to use this version for oc2.0.3.1 but I get the following error:
PHP Notice: Undefined index: name in /public_html/admin/controller/report/engagement_pro.php on line 176

line 176:
176:  $format_repeat[$i]['products'][$p]['name'] = $product['name'];

**Comment by mochacat** [comment]
Hi, try the latest version in Master. The catalog's model file was missing from the repo.

**Comment by aljawaid** [comment]
Hello, I re-downloaded and reinstalled your extension but I get the same error on line 176.

There seems to be something wrong with this:
line 176:
$format_repeat[$i]['products'][$p]['name'] = $product['name'];

**Comment by mochacat** [comment]
I have it running on a clean install for v.2.0.3.1 but cannot replicate the error. Can you tell me more about your store environment? Are you working with a clean install, 0 products, or many products? Do you have any modifications to the core files, such as a modification of the function getProducts in admin/controller/product.php? Is 'name'  still a field for the product_description table for your OC store?

**Comment by aljawaid** [comment]
Are you working with a clean install, 0 products, or many products?
- clean install 2.0.3.1 with around 150 test products (not selling live yet but on a live server)

Do you have any modifications to the core files, such as a modification of the function getProducts in admin/controller/product.php?
- need to check, will check now

Is 'name' still a field for the product_description table for your OC store?
- yes, table oc_product_description has the field 'name' set as 'varchar(255)'

**Comment by aljawaid** [comment]
I have plenty of extensions installed but when comparing yours with the original file, I notice this below.  Not sure if it helps though?

< admin/controller/catalog/product.php >
under: $results = $this->model_catalog_product->getProducts($filter_data);
this is the default:
'name'       => $result['name'],

**Comment by mochacat** [comment]
Thanks for the info. Sorry that was a typo, I meant getProduct, not getProducts. It's a short function that looks like this:

```
public function getProduct($product_id) {
        $query = $this->db->query("SELECT DISTINCT *, (SELECT keyword FROM " . DB_PREFIX . "url_alias WHERE query = 'product_id=" . (int)$product_id . "') AS keyword FROM " . DB_PREFIX . "product p LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p.product_id = '" . (int)$product_id . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "'");

        return $query->row;
}
```

**Comment by aljawaid** [comment]
THAT function is in the default **model** file **not** the controller.

admin/model/catalog/product.php
public function getProduct($product_id) {

**Comment by aljawaid** [comment]
In my **vq2_system_modification_admin_model_catalog_product.php** this is what I have:

```
public function getProduct($product_id) {
        $query = $this->db->query("SELECT DISTINCT *, (SELECT keyword FROM " . DB_PREFIX . "url_alias WHERE query = 'product_id=" . (int)$product_id . "') AS keyword FROM " . DB_PREFIX . "product p LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p.product_id = '" . (int)$product_id . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "'");

        return $query->row;
    }
```

**Comment by mochacat** [comment]
Yeah sorry about that, I meant model not controller. It looks like nothing is different. I'll have more time next week to play around with my install to see if I can trigger that specific error. I'll keep this issue open until I'm able to find a cause.
